name: Teste Flask com GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código-fonte
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Instalar dependências
      run: |
        python3 -m venv .venv
        source ./.venv/bin/activate
        poetry install --no-dev

    - name: Iniciar aplicação Flask
      run: |
        source ./.venv/bin/activate
        python .venv/bin/flask --app main run

    - name: Aguardar um tempo para a aplicação iniciar
      run: sleep 5

    - name: Executar testes com pytest
      run: |
        source ./.venv/bin/activate
        pytest
