name: Teste Flask com GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código-fonte
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only main

    - name: Iniciar aplicação Flask
      run: |
        flask --app main run

    - name: Aguardar um tempo para a aplicação iniciar
      run: sleep 5

    - name: Executar testes com pytest
      run: |
        pytest