name: Teste Flask e CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Instalar dependências
      run: |
        python3 -m venv .venv
        source ./.venv/bin/activate
        pip install poetry
        poetry install --only main

    - name: Iniciar servidor Gunicorn para Flask
      run: |
        source ./.venv/bin/activate
        gunicorn -b 127.0.0.1:5000 main:app &  # Inicia o servidor Gunicorn para o Flask

    - name: Aguardar um tempo para a aplicação iniciar
      run: sleep 5  # Aguarda alguns segundos para o Flask iniciar

    - name: Executar testes com pytest
      run: |
        source ./.venv/bin/activate
        pytest